### PR TITLE
Hotfix/0.41

### PR DESCRIPTION
**Pull request by seb-mueller**
I came accros a few errors I encountered running the 0.4 version on the shipped test data:
```
snakemake --use-conda --conda-prefix ~/.conda/myenv --directory .test -p
```
This hotfix should fix them and should be gitflow merged into both master and develop I suppose.

### CODE REVIEW

**Comment by seb-mueller** [comment]
Travis still isn't happy throwing the error below. I can't reproduce this error, but will investigate.
I'd add the R debug code (saving R objects) in as discussed before. Would you object this to include in the official code, since it would make debugging a lot easier?

Edit: This thread seems to have found the same issue specific to Travis:
https://stackoverflow.com/questions/52649772/what-is-causing-must-request-at-least-one-colour-from-a-hue-palette-error-in-m

```
[Mon Feb 11 14:16:20 2019]
localrule plot_adapter_content:
    input: results/logs/cutadapt/sample1.clean_qc.csv, results/logs/cutadapt/sample2.clean_qc.csv
    output: results/plots/adapter_content.pdf
    jobid: 4
    wildcards: results_dir=results
Rscript --vanilla /home/travis/build/Hoohm/dropSeqPipe/.test/.snakemake/scripts/tmp09q6yr01.plot_adapter_content.R
Activating conda environment: /home/travis/build/Hoohm/dropSeqPipe/.test/.snakemake/conda/a6153eb6
Attaching package: ‘dplyr’
The following objects are masked from ‘package:stats’:
    filter, lag
The following objects are masked from ‘package:base’:
    intersect, setdiff, setequal, union
Saving 7 x 7 in image
Error: Must request at least one colour from a hue palette.
Execution halted
```

**Comment by seb-mueller** [comment]
Catching the error seems to do the trick. Not sure if someone can reproduce, but travis gave this result upon `message(str(data))`:

```
Classes ‘grouped_df’, ‘tbl_df’, ‘tbl’ and 'data.frame':	24 obs. of  6 variables:
 $ Sample     : chr  "sample1" "sample2" "sample1" "sample2" ...
 $ Batch      : chr  "Batch1" "Batch2" "Batch1" "Batch2" ...
 $ Adapter    : Factor w/ 6 levels "PrefixNX/1","PrefixNX/2",..: NA NA NA NA NA NA NA NA NA NA ...
 $ Pair       : Factor w/ 2 levels "R1","R2": NA NA NA NA NA NA NA NA NA NA ...
 $ Count      : int  7 15 0 0 6 3 22 91 8 1 ...
 $ Percentages: num  0.0761 0.0898 0 0 0.0652 ...

```
compared to my local test (following the exact same steps as travis):

``` 
Classes ‘grouped_df’, ‘tbl_df’, ‘tbl’ and 'data.frame': 24 obs. of  6 variables:
 $ Sample     : chr  "sample1" "sample2" "sample1" "sample2" ...
 $ Batch      : chr  "Batch1" "Batch2" "Batch1" "Batch2" ...
 $ Adapter    : Factor w/ 6 levels "PrefixNX/1","PrefixNX/2",..: 1 1 2 2 3 3 4 4 5 5 ...
 $ Pair       : Factor w/ 2 levels "R1","R2": 1 1 1 1 1 1 1 1 1 1 ...
 $ Count      : int  7 15 0 0 6 3 22 91 8 1 ...
 $ Percentages: num  0.146 0.13 0 0 0.125 ...
```

**Comment by Hoohm** [comment]
I'm getting this 'NA' issue when I run it locally.
Trying to fix it

**Comment by Hoohm** [comment]
I've sent a commit reverting the changes to the factors that seems to work for me.
Also, I fixed the batches facet_wrap.

**Comment by seb-mueller** [comment]
Where did you do you submit this commit? Also, could you send me your workspace and sessionInfo? I still wonder where it goes wrong, so comparing might shed some light.

**Comment by Hoohm** [comment]
I think you got a PR on your hotfix branch.
Here is the sessionInfo:
```
 [1] Rcpp_1.0.0       assertthat_0.2.0 crayon_1.3.4     R6_2.2.2        
 [5] grid_3.4.1       plyr_1.8.4       gtable_0.2.0     magrittr_1.5    
 [9] scales_1.0.0     pillar_1.3.0     rlang_0.2.1      stringi_1.2.4   
[13] lazyeval_0.2.1   tools_3.4.1      glue_1.3.0       munsell_0.5.0   
[17] compiler_3.4.1   pkgconfig_2.0.2  colorspace_1.3-2 bindr_0.1.1     
[21] tibble_1.4.2    

```

**Comment by seb-mueller** [comment]
Hmm, can't find any commits anywhere.. Could share the link here? Also, if this is easy to do, could you share the workspace at the point where it breaks?

**Pull request merged**
