### PR TITLE
Add new parameters, fix plotting

### PR DESCRIPTION
**Pull request by martinholub**
Hello @Hoohm,

I have used the dropSeqPipe for DroNc-seq data analysis and found it a great help. I like that it chains the commands into reproducible workflow. Thumbs up!

I made small adjustments to the pipeline, mainly because I needed to access additional parameters other than the ones you decided to expose in the configuration file. I create a pull request as you may benefit from looking at the changes and considering if other users would need them as well.

I also had to make small changes to `knee_plot.R` and disable `BCDrop` plot as these were not running out of the box. I would further suggest that add a note to WIKI regarding the fact that one needs to generate index with the same `--sjdbOverhang` as is used later for alignment.

### CODE REVIEW

**Comment by Hoohm** [comment]
Hello @martinholub 
I'm glad the pipeline is useful for you 👍 

I'm currently working on a new release. I'm getting rid of the python package style and coming back to snakemake workflows. This would also enable an easier access to parameters that are not exposed right now.
I hope to release it in a week or two.

I've never been familiar with java options and I see you added XX:ParallelGCThreads={CORES}. How would this work on local computers as opposed to clusters? Does it speed up the processes? I always thought the bottleneck here was i/O access.

Could you tell me what wasn't working out of the box for BCDrop? I really like the plot and I would like to keep it.

The STAR index generation will now be included in the pipeline as a prerequisite (as would any files necessary for the mapping steps). This will make it simpler to use.

Wish you a happy new year

**Comment by martinholub** [comment]
Hello @Hoohm ,

excuse my delayed response. Regarding your questions: 
* I did not run the pipeline locally, only on cluster, and there `_JAVA_OPTIONS -XX:ParallelGCThread` defaults to `1`, as a result only one core was available to Picard and DropSeq. I noticed improved performance with allowing usage of multiple cores. I haven't timed it though. Note that similar result could have been probably achieved by calling `_JAVA_OPTIONS -XX:ParallelGCThread=<num_cores>` before the pipeline command. 

* I will get back to you regarding the `plotBCDrop`, currently I cannot reproduce it as our cluster is down due to maintenance. As far as I remember, it was basically `index out of bounds` error when indexing the `data` data frame. The error message was unfortunately not very useful so I didn't manage to fix it.

**Comment by martinholub** [comment]
Hello @Hoohm ,
here is the error message I get:
```
Error in x[[jj]][iseq] <- vjj : replacement has length zero
Calls: plotBCDrop -> [<- -> [<-.data.frame
```

**Comment by Hoohm** [comment]
Is it possible that you have some empty logfiles from *CELL_barcode.txt and *UMI_barcode.txt?
I've run into this issue when the filters are too stringent and the plotting will fail because of no lines to read from.

**Comment by martinholub** [comment]
None of these files are empty (see attached).
[barcodes.zip](https://github.com/Hoohm/dropSeqPipe/files/1616036/barcodes.zip)

**Comment by Hoohm** [comment]
I might have the issue. Did you run the fastqc step?

**Review by Hoohm — CHANGES_REQUESTED** [review]
I think you mistook an argument for DetectBeadSynthesisErrors.

Line 77 NUM_UMIS_PER_CELL, did you mean MIN_UMIS_PER_CELL?

**Comment by martinholub** [comment]
you are correct, thanks for the tip.

Regarding the fastqc - I have run it only on couple of files, not for all that I have used in the downstream pipeline. 
I will rerun `fastqc` and `generate-plots` to see if it solves the issue.

**Comment by martinholub** [comment]
update: `generate-plots` still errors the same way, even if it has output of `fastqc` available.

**Comment by Hoohm** [comment]
Edit:
I think it won't work if you run only part of the fastqc. This is fixed in the new BCdrop because it doesn't rely on the summary fastqc.txt file anymore.

**Comment by Hoohm** [comment]
Hello @martinholub,
this should be fixed in the new version.
I'm not keen on exposing this option since I'm not sure how it would be useful in this context.
Could you tell me how you use it and for what purpose. Maybe we can even improve the pipeline on this.

**Pull request closed without merging**
