### PR TITLE
Fix plot rna metrics.r & extract_expression_single.smk

### PR DESCRIPTION
**Pull request by cgirardot**
`plot_rna_metrics.R` fails due to `snakemake@input[[1]]` when used in the context of `extract_expression_species.smk`. Had to ensure input is also named in the context of `extract_expression_single.smk`

### CODE REVIEW

**Comment by Hoohm** [comment]
Thanks for the quick fix. Can you make a second PR fr the dev branch plz?

**Comment by cgirardot** [comment]
I did, I hope, I am not so fluent with all github operations. 
Also can you simply propagate the merge into your dev branch ? I believe that s what guys in my team do. 

best 

C


> On 7. Nov 2018, at 13:38, Patrick Roelli <notifications@github.com> wrote:
> 
> Thanks for the quick fix. Can you make a second PR fr the dev branch plz?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

=====================================
Charles Girardot
Head of Genome Biology Computational Support (GBCS)
and Senior Bioinformatician in the Furlong Lab
European Molecular Biology Laboratory
Tel: +49 6221 387 -8585
Fax: +49-(0)6221-387-8166 
Email: charles.girardot@embl.de
Skype: charles_girardot
Web : http://gbcs.embl.de
Room V205
Meyerhofstraße 1, 
69117 Heidelberg, Germany
=====================================

**Comment by Hoohm** [comment]
To be honest I'm also still learning here.
We're trying to use git flow to structure the project but the integration of PR for features/bugfixes/hotfixes is still kind of fuzzy to me.

Are you sure you did a PR for master and develop? I can't see the develop PR

**Comment by cgirardot** [comment]
sorry I did the reverse, PR from your develop to my branch :-/

you should see it now
best 

Charles

> On 8. Nov 2018, at 09:37, Patrick Roelli <notifications@github.com> wrote:
> 
> To be honest I'm also still learning here.
> We're trying to use git flow to structure the project but the integration of PR for features/bugfixes/hotfixes is still kind of fuzzy to me.
> 
> Are you sure you did a PR for master and develop? I can't see the develop PR
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

=====================================
Charles Girardot
Head of Genome Biology Computational Support (GBCS)
and Senior Bioinformatician in the Furlong Lab
European Molecular Biology Laboratory
Tel: +49 6221 387 -8585
Fax: +49-(0)6221-387-8166 
Email: charles.girardot@embl.de
Skype: charles_girardot
Web : http://gbcs.embl.de
Room V205
Meyerhofstraße 1, 
69117 Heidelberg, Germany
=====================================

**Pull request merged**
